### ISSUE TITLE
Mmh...

### ISSUE THREAD

**Issue by 4skinSkywalker** [BeachumMichael/Racer-3LA#1]
This looks exactly like the one I've been working on: [Zinga Burga](https://github.com/4skinSkywalker/Zinga-Burga)

**Comment by BeachumMichael** [comment]
Nice to see someone else was able to make one too! I looked at the repository and love all the information. Didn't know you had one going but nice work with the files. Please contact me if you'd like to talk more about the project. Please let me know which platform you would like.

**Comment by 4skinSkywalker** [comment]
Yeah, nice stuff! :)
You can ping me on Telegram @FredoCorleone
